config/routes.rb
Onetree::Application.routes.draw do

   devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'create_new_onetree' }

   root :to => 'home#index'
   match 'projects/project_show_via_ajax_call' => 'projects#project_show_via_ajax_call'
   
   resources :projects
   resources :services
   resources :content_management

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :client, :title, :description, :url
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :title, :icon, :description
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def bring_in_models
      @projects = Project.order("id DESC")
      @services = Service.all
  end
  
end

app/controllers/content_management_controller.rb
class ContentManagementController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    bring_in_models
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    bring_in_models
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!

    def new
      @project = Project.new
    end

    def create
      @project = Project.create(params[:project])
      respond_to do |format|
        if @project.save
          format.html { redirect_to content_management_index_path }
        else
          format.html { redirect_to new_project_path, :notice => "Cannot create product without a title!" }
        end
      end
    end

    def show
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end
    
    def project_show_via_ajax_call
      project = Project.find(params[:id])
      #next_project = project.next
      #next_project_id = next_project.map {|np| np.id}.join("")
      #prev_project = project.prev
      #prev_project_id = prev_project.map {|pp| pp.id}.join("")
      
      video = project.url
      project_show = { :id => project.id, :title => project.title, :client => project.client, :description => project.description, :video => video }
      render :json => project_show
    end

    def index
      @project = Project.all
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end

    def edit
      @project = Project.find(params[:id])
    end

    def update   
      @project = Project.find(params[:id])
      if @project.update_attributes(params[:project])
        respond_to do |format|
         format.html { redirect_to content_management_index_path }
        end
      else
        render :action => 'edit'
      end
    end

    def destroy
      @project = Project.find(params[:id])
      @project.destroy
      respond_to do |format|
        format.html { redirect_to content_management_index_path }
      end
    end
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :authenticate_user!

    def new
      @service = Service.new
    end

    def create
      @service = Service.create(params[:service])
      respond_to do |format|
        if @service.save
          format.html { redirect_to content_management_index_path }
        else
          format.html { redirect_to new_service_path, :notice => "Cannot create service without a title!" }
        end
      end
    end

    def show
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end

    def index
      @service = Service.all
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end

    def edit
      @service = Service.find(params[:id])
    end

    def update   
      @service = Service.find(params[:id])
      if @service.update_attributes(params[:service])
        respond_to do |format|
         format.html { redirect_to content_management_index_path }
        end
      else
        render :action => 'edit'
      end
    end

    def destroy
      @service = Service.find(params[:id])
      @service.destroy
      respond_to do |format|
        format.html { redirect_to content_management_index_path }
      end
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_management_helper.rb
module ContentManagementHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/content_management/_projects.html.erb
<div class="cmsWrapper">
	<div class="releases">
		<div class="divHeader">Projects</div>
		<div class="tableWrapper">
			<div class="tableContent">
				<% if @projects.count > 0 %>
					<table width="100%">
						<tr class="tableHeader">
							<th>CLIENT</th>
							<th>PROJECT</th>
							<th>URL</th>
						</tr>
						<tr><hr class="ruler"/></tr>
						<% @projects.each do |p| %>
							<tr class="tableRow">
								<td width="22%"><%= p.client %></td>
								<td width="22%"><%= p.title %></td>
								<td width="50%"><%= link_to "http://vimeo.com/#{p.url}", "http://vimeo.com/#{p.url}", :target => "_blank" %></td>
								<td width="3%"><%= link_to image_tag('edit2.png'), edit_project_path(p) %></td>
							</tr>
						<% end %>
					</table>
				<% else %>
					<table width="100%"><tr class="tableRow empty"><td><em>YOU HAVE NO PROJECTS YET... ADD SOME BELOW ?!</em></td></tr></table>
				<% end %>
			</div>
			<div id="person-form" title="Person" style="display:none"></div>
		</div>
	</div>
	<h6><%= link_to 'Add new project', new_project_path, :class => "darkButton2" %></h6>
</div>

app/views/content_management/_services.html.erb
<div class="cmsWrapper">
	<div class="releases">
		<div class="divHeader">Services</div>
		<div class="tableWrapper">
			<div class="tableContent">
				<% if @services.count > 0 %>
					<table width="100%">
						<tr class="tableHeader">
							<th>TITLE</th>
							<th>ICON-NAME</th>
							<th>DESCRIPTION</th>
						</tr>
						<tr><hr class="ruler"/></tr>
						<% @services.each do |s| %>
							<tr class="tableRow">
								<td width="22%"><%= truncate(s.title, :length => 22) %></td>
								<td width="16%"><%= s.icon %></td>
								<td width="59%"><%= truncate(s.description, :length => 65, :separator => ' ') %></td>
								<td width="3%"><%= link_to image_tag('edit2.png'), edit_service_path(s) %></td>
							</tr>
						<% end %>
					</table>
				<% else %>
					<table width="100%"><tr class="tableRow empty"><td><em>YOU HAVE NO SERVICES YET... ADD SOME BELOW ?!</em></td></tr></table>
				<% end %>
			</div>
			<div id="person-form" title="Person" style="display:none"></div>
		</div>
	</div>
</div>

app/views/content_management/index.html.erb
<section class="cmsBacker parallax2">

	<div class="">
		<!-- Your Logo -->
		<%= image_tag('logo-icon-m.png') %>
	</div>
	
	<div class="title grid-full">
		<h2 class="bold">Manage your website's content</h2>
		<div class="minusTop"><%= link_to "{ HOME }", root_path %></div>
		<span class="border"></span>
	</div>

	<%= render partial: 'projects' %>
	<%= render partial: 'services' %>
	
</section>

app/views/home/_blockquote.html.erb
<!-- Blockquote -->
<section id="blockquote">

	<div class="inner no-padding">
		<!-- Your Text -->
		<p class="normal white blockquote italic"><em>"Music is a moral law. It gives soul to the universe, wings to the mind, flight to the imagination, and charm and gaiety to life and to everything."</em>
		</p><br/> - PLATO
	</div>

</section><!-- End Blockquote Section -->

app/views/home/_clients.html.erb
<!-- Testimonials -->
<section id="clients" class="clients parallax2">

	<div class="inner clientimages">

		<ul class="inline">
			<li class="padded"><%= image_tag('clients/HSBC.png') %></li>
			<li class="padded"><%= image_tag('clients/coke.png') %></li>
			<li class="padded"><%= image_tag('clients/toyota.png') %></li>
			<li class="padded"><%= image_tag('clients/guiness.png') %></li>
			<li class="padded"><%= image_tag('clients/jaguar.png') %></li>
			<li class="padded"><%= image_tag('clients/ogilvy.png') %></li>
			<li class="padded"><%= image_tag('clients/reebok.png') %></li>
			<li class="padded"><%= image_tag('clients/saatchi.png') %></li>
			<li class="padded"><%= image_tag('clients/sky.png') %></li>
			<li class="padded"><%= image_tag('clients/DLKW.png') %></li>
			<li class="padded"><%= image_tag('clients/gridtrax.png') %></li>
			<li class="padded"><%= image_tag('clients/tag.png') %></li>
			<li class="padded"><%= image_tag('clients/closeup.png') %></li>
			<li class="padded"><%= image_tag('clients/unilver.png') %></li>
		</ul>

	</div><!-- End Inner Div -->

</section><!-- End Testimonials Section -->

app/views/home/_contact.html.erb
<!-- Contact Section -->
<section id="contact" class="container parallax5">
	<!-- Contact Inner -->
	<div class="inner contact">

		<!-- Header -->
		<h1 class="header semibold white">Get In <span class="extrabold">Touch</span></h1>

		<!-- Description -->
		<h4 class="h-desc white contact-text">On the other hand, we denounce with righteous indignation and dislike men who are so beguiled. </h4>

		<!-- Form Area -->
		<div class="contact-form">
			<!-- Form -->
			<form id="contact-us" method="post" action="php/mail.php">
				<!-- Left Inputs -->
				<div class="col-xs-6 animated" data-animation="fadeInLeft" data-animation-delay="300">
					<!-- Name -->
					<input type="text" name="name" id="name" required="required" class="form light" placeholder="Name" />
					<!-- Email -->
					<input type="email" name="mail" id="mail" required="required" class="form light" placeholder="Email" />
					<!-- Subject -->
					<input type="text" name="subject" id="subject" required="required" class="form light" placeholder="Subject" />
				</div><!-- End Left Inputs -->
				<!-- Right Inputs -->
				<div class="col-xs-6 animated" data-animation="fadeInRight" data-animation-delay="300">
					<!-- Message -->
					<textarea name="message" id="message" class="form textarea light"  placeholder="Message"></textarea>
				</div><!-- End Right Inputs -->
				<!-- Bottom Submit -->
				<div class="relative fullwidth col-xs-12">
					<!-- Send Button -->
					<button type="submit" id="submit" name="submit" class="form-btn light">Send Message</button> 
				</div><!-- End Bottom Submit -->
				<!-- Clear -->
				<div class="clear"></div>
			</form>

			<!-- Your Mail Message -->
			<div class="mail-message-area">
				<!-- Message -->
				<div class="alert gray-bg mail-message not-visible-message">
					<strong>Thank You !</strong> Your email has been delivered.
				</div>
			</div>

		</div><!-- End Contact Form Area -->
	</div><!-- End Inner -->
</section><!-- End Contact Section -->

app/views/home/_fun.html.erb
<!-- Fun Acts -->
<section id="fun-acts" class="container">

	<div class="inner">

		<!-- Company Facts -->
		<div class="facts">


			<!-- Factor -->
			<div class="col-xs-3 fact">
				<!-- Fact Left -->
				<a class="fact-icon">
					<!-- Fact Icon -->
					<i class="fa fa-briefcase"></i>
				</a>
				<!-- Factor Area -->
				<div class="fact-number" data-perc="1231">
					<!-- Factor -->
					<h1 class="factor light"></h1>
					<!-- Factor Description -->
					<h3 class="light uppercase">Searches completed</h3>
				</div><!-- End Factor Area -->
			</div><!-- End Factor -->


			<!-- Factor -->
			<div class="col-xs-3 fact">
				<!-- Fact Left -->
				<a class="fact-icon">
					<!-- Fact Icon -->
					<i class="fa fa-pagelines"></i>
				</a>
				<!-- Factor Area -->
				<div class="fact-number" data-perc="463">
					<!-- Factor -->
					<h1 class="factor"></h1>
					<!-- Factor Description -->
					<h3 class="light uppercase">Original compositions</h3>
				</div><!-- End Factor Area -->
			</div><!-- End Factor -->


			<!-- Factor -->
			<div class="col-xs-3 fact">
				<!-- Fact Left -->
				<a class="fact-icon">
					<!-- Fact Icon -->
					<i class="fa fa-comments"></i>
				</a>
				<!-- Factor Area -->
				<div class="fact-number" data-perc="153">
					<!-- Factor -->
					<h1 class="factor light"></h1>
					<!-- Factor Description -->
					<h3 class="light uppercase">Satisfied clients</h3>
				</div><!-- End Factor Area -->
			</div><!-- End Factor -->


			<!-- Factor -->
			<div class="col-xs-3 fact">
				<!-- Fact Left -->
				<a class="fact-icon">
					<!-- Fact Icon -->
					<i class="fa fa-coffee"></i>
				</a>
				<!-- Factor Area -->
				<div class="fact-number" data-perc="3713">
					<!-- Factor -->
					<h1 class="factor light"></h1>
					<!-- Factor Description -->
					<h3 class="light uppercase">Macchiatos</h3>
				</div><!-- End Factor Area -->
			</div><!-- End Factor -->

			<!-- Clear -->
			<div class="clear"></div>
		</div><!-- End Company Facts -->

	</div><!-- End Fun Acts Inner -->

</section><!-- End Fun Acts Section -->

app/views/home/_hero.html.erb
<!-- Home Section -->
<section id="home" class="relative"> 	
	<div id="slides">
		<div class="slides-container relative">
			<!-- Slider Images -->
			<div class="image1"></div>
			<div class="image2"></div>
			<div class="image3"></div>
			 <!-- End Slider Images -->	 
		</div>
	</div><!-- End Home Slides -->
	<div class="v2 absolute">
		<!-- Auto Typocraphic Texts -->
		<div class="typographic">
			<h1 class=" condensed uppercase no-padding no-margin bold">welcome to</h1>
			<h1 class=" condensed uppercase no-padding no-margin bold colored">one tree music</h1>
			<h3 class=" condensed uppercase no-padding no-margin bold size">passionate about music &amp; image</h3>
		</div><!--End Auto Typocraphic Texts -->
		<!-- Bottom Arrow -->
		<a href="#about" class="home-arrow scroll uppercase bold">
			<img src="assets/bottom-arrow.png" alt="bottom" />
			<span class="white">what we do ?</span>
		</a>
	</div><!-- End V2 area -->
</section><!-- End Home Section -->

app/views/home/_history.html.erb
<!-- History -->
<section id="history" class="container parallax3">

	<div class="inner history">

		<!-- Header -->
		<h1 class="header light dark"><span class="condiment">One Tree Music</span> History</h1>

		<!-- Description -->
		<h4 class="h-desc dark">One Tree Music was founded by David Wille in 2010 in response to requests from his peers for advice and help in the music rights and sponsorship space. Having informally helped producers, creatives and brands to find and work with compelling and unique artists he grew the client base to include some of the worlds best known brands. </h4>

		<ul class="timeline">

			<!-- Time -->
			<li class="time today"><%= Date.today.year %></li>

			<!-- Note -->
			<li class="note animated" data-animation="fadeInRight" data-animation-delay="200">
				<!-- Date -->
				<p class="history-date no-margin uppercase normal">2nd June 2014</p>

				<!-- Header -->
				<p class="history-head uppercase semibold">HSBC PREMIER</p>

				<!-- Description -->
				<p class="history-desc no-margin normal">We beat competition from 4 other music production houses, and over 60 composers to produce the music for the three part, global advertising campaign for HSBC's new, premium bank account</p>

				<!-- Images -->
				<div class="timeline-images">
					<a href="http://vimeo.com/96887218"  data-rel="prettyPhoto[gallery2]" class="timeline-image"><img src="assetsvideo.png" alt="" /></a>
					
				</div>
				<!-- Arrow -->
				<span class="note-arrow"></span>
			</li>
			
			<!-- Time -->
			<li class="time">2014</li>

			<!-- Note -->
			<li class="note animated" data-animation="fadeInRight" data-animation-delay="200">
				<!-- Date -->
				<p class="history-date no-margin uppercase normal">DATE?!?!?!?!</p>

				<!-- Header -->
				<p class="history-head uppercase semibold">ANOTHER KEY BIT OF WORK FROM 2010</p>

				<!-- Description -->
				<p class="history-desc no-margin normal">Following hot on the heels of project one was project two where we did this that and the other</p>

				<!-- Images -->
				<div class="timeline-images">
				</div>
				<!-- Arrow -->
				<span class="note-arrow"></span>
			</li>

			<!-- Note -->
			<li class="note animated" data-animation="fadeInLeft" data-animation-delay="200">
				<!-- Date -->
				<p class="history-date no-margin uppercase normal">DATE?!?!?!?</p>

				<!-- Header -->
				<p class="history-head uppercase semibold">One Tree Music Arrives </p>

				<!-- Description -->
				<p class="history-desc no-margin normal">Having set up the company we quickly got running, with this campaign for this client.</p>

				<!-- Images -->
				<div class="timeline-images">
					<a href="http://vimeo.com/55945051"  data-rel="prettyPhoto[gallery6]" class="timeline-image"><img src="assets/video.png" alt="" /></a>
				</div>
				<!-- Arrow -->
				<span class="note-arrow"></span>
			</li>

			<!-- Start Icon -->
			<li class="start"><a href="#history" class="scroll dark-gray-degrade-diagonal"><span class="up-arrow"></span></a></li>
			<li class="clear"></li>
		</ul>

	</div><!-- End Inner Div -->

</section><!-- End History Section -->

app/views/home/_map.html.erb
<!-- Google Map Section -->
<section id="map" class="container close-map">
	<!-- Open/Close Button -->
	<a id="map-button" class="google-map-big-button uppercase bold condensed white scroll close-map-button" href="#map" >where are we ? click for google map <i class="fa fa-caret-down"></i></a>
	<!-- Google Map Script -->
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
	<!-- Google Map -->
	<div id="google-map"></div>
</section><!-- End Google Map Section -->

app/views/home/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
    	<div class="modal-content windowModal">
			<img class="projectPreloader" src="assets/loading.gif" style="display:none;">
			<div class="modal-fade">
				
			</div>
		</div>
  	</div>
</div>

app/views/home/_our_aim.html.erb
<!-- About -->
<section id="about" class="container waypoint">
	<div class="inner">
		<!-- Header -->
		<h1 class="header semibold light">We seek, identify &amp;<span class="colored"> deliver</span> the best music &amp; artists for any campaign.</h1>
		<!-- Description -->
		<h2 class="semibold light">We produce the highest quality film and images for <span class="colored">your</span> brand campaign.</h2>
		<!-- Boxes -->
		
	</div><!-- End About Inner -->
</section><!-- End About Section -->

app/views/home/_portfolio.html.erb
<!-- Portfolio -->
<section id="portfolio" class="container">

	<div class="portfolio">

		<!-- Header -->
		<h1 class="header light dark"><span class="condiment">Oxygen's Portfolio</span></h1>

		<!-- Description -->
		<h4 class="h-desc dark">On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and by the <span class="dark bold">charms</span> of pleasure of the moment, so blinded by desire, that they cannot foresee the pain </h4>

	</div><!-- End inner div -->

		<!-- Expander -->
		<div class="item-expander relative">
			<div id="item-expander">
				<p class="cls-btn"><a class="close">X</a></p>
				<div class="expander-inner"></div>
			</div>
		</div>

		<!-- Filters -->
		<div id="options" class="filter-menu fullwidth">
			<ul id="filters" class=" option-set relative normal" data-option-key="filter">
				<li><a href="#filter" data-option-value="*" class="selected">show all</a></li>
				<li><a href="#filter" data-option-value=".design">design</a></li>
				<li><a href="#filter" data-option-value=".photography">photography</a></li>
				<li><a href="#filter" data-option-value=".video">video</a></li>
				<li><a href="#filter" data-option-value=".art">art</a></li>
			</ul>
		</div>

		<!-- Works -->
		<div class="portfolio-items no-margin no-padding">

			<!-- Work -->
			<div class="work five design ">
				<div class="work-inner">
					<!-- Image -->
					<div class="work-image">
						<a href="projects/project-1.html" class="expander">
							<img src="images/portfolio/1.jpg" alt="" />
							<span class="positive"></span>
						</a>
					</div>
					<!-- Work Details -->
					<div class="work-bottom">
						<p class="work-name uppercase normal no-margin">Work image 1</p>
						<p class="work-category normal no-margin">Design</p>
						<a href="images/portfolio/slide2.jpg"  data-rel="prettyPhoto[gallery]" class="work-link" ><span class="arrow"></span></a>
					</div>
				</div><!-- End Work Inner -->
			</div><!-- End Work -->

			<!-- Work -->
			<div class="work five video photography">
				<div class="work-inner">
					<!-- Image -->
					<div class="work-image">
						<a href="projects/project-2.html" class="expander">
							<img src="images/portfolio/2.jpg" alt="" />
							<span class="positive"></span>
						</a>
					</div>
					<!-- Work Details -->
					<div class="work-bottom">
						<p class="work-name uppercase normal no-margin">Work image 2</p>
						<p class="work-category normal no-margin">Design</p>
						<a class="work-link-passive" ><span class="arrow"></span></a>
					</div>
				</div><!-- End Work Inner -->
			</div><!-- End Work -->

			<!-- Work -->
			<div class="work five art video">
				<div class="work-inner">
					<!-- Image -->
					<div class="work-image">
						<a href="projects/project-3.html" class="expander">
							<img src="images/portfolio/3.jpg" alt="" />
							<span class="positive"></span>
						</a>
					</div>
					<!-- Work Details -->
					<div class="work-bottom">
						<p class="work-name uppercase normal no-margin">Work image 3</p>
						<p class="work-category normal no-margin">Design</p>
						<a  href="images/portfolio/slide1.jpg"  data-rel="prettyPhoto[gallery]" class="work-link"  ><span class="arrow"></span></a>
					</div>
				</div><!-- End Work Inner -->
			</div><!-- End Work -->

			<!-- Work -->
			<div class="work five design art">
				<div class="work-inner">
					<!-- Image -->
					<div class="work-image">
						<a href="projects/project-4.html" class="expander">
							<img src="images/portfolio/4.jpg" alt="" />
							<span class="positive"></span>
						</a>
					</div>
					<!-- Work Details -->
					<div class="work-bottom">
						<p class="work-name uppercase normal no-margin">Work image 4</p>
						<p class="work-category normal no-margin">Design</p>
						<a class="work-link-passive" ><span class="arrow"></span></a>
					</div>
				</div><!-- End Work Inner -->
			</div><!-- End Work -->

			<!-- Work -->
			<div class="work five design video">
				<div class="work-inner">
					<!-- Image -->
					<div class="work-image">
						<a href="projects/project-5.html" class="expander">
							<img src="images/portfolio/5.jpg" alt="" />
							<span class="positive"></span>
						</a>
					</div>
					<!-- Work Details -->
					<div class="work-bottom">
						<p class="work-name uppercase normal no-margin">Work image 5</p>
						<p class="work-category normal no-margin">Design</p>
						<a href="images/portfolio/slide3.jpg"  data-rel="prettyPhoto[gallery]"  class="work-link" ><span class="arrow"></span></a>
					</div>
				</div><!-- End Work Inner -->
			</div><!-- End Work -->

			<!-- Work -->
			<div class="work five art photography">
				<div class="work-inner">
					<!-- Image -->
					<div class="work-image">
						<a href="projects/project-1.html" class="expander">
							<img src="images/portfolio/6.jpg" alt="" />
							<span class="positive"></span>
						</a>
					</div>
					<!-- Work Details -->
					<div class="work-bottom">
						<p class="work-name uppercase normal no-margin">Work image 6</p>
						<p class="work-category normal no-margin">Design</p>
						<a href="images/portfolio/slide4.jpg"  data-rel="prettyPhoto[gallery]"  class="work-link" ><span class="arrow"></span></a>
					</div>
				</div><!-- End Work Inner -->
			</div><!-- End Work -->

			<!-- Work -->
			<div class="work five design photography video">
				<div class="work-inner">
					<!-- Image -->
					<div class="work-image">
						<a href="projects/project-2.html" class="expander">
							<img src="images/portfolio/7.jpg" alt="" />
							<span class="positive"></span>
						</a>
					</div>
					<!-- Work Details -->
					<div class="work-bottom">
						<p class="work-name uppercase normal no-margin">Work image 7</p>
						<p class="work-category normal no-margin">Design</p>
						<a class="work-link-passive" ><span class="arrow"></span></a>
					</div>
				</div><!-- End Work Inner -->
			</div><!-- End Work -->

			<!-- Work -->
			<div class="work five video photography art">
				<div class="work-inner">
					<!-- Image -->
					<div class="work-image">
						<a href="projects/project-3.html" class="expander">
							<img src="images/portfolio/8.jpg" alt="" />
							<span class="positive"></span>
						</a>
					</div>
					<!-- Work Details -->
					<div class="work-bottom">
						<p class="work-name uppercase normal no-margin">Work image 8</p>
						<p class="work-category normal no-margin">Design</p>
						<a href="images/portfolio/slide5.jpg"  data-rel="prettyPhoto[gallery]"  class="work-link" ><span class="arrow"></span></a>
					</div>
				</div><!-- End Work Inner -->
			</div><!-- End Work -->

			<!-- Work -->
			<div class="work five art">
				<div class="work-inner">
					<!-- Image -->
					<div class="work-image">
						<a href="projects/project-4.html" class="expander">
							<img src="images/portfolio/9.jpg" alt="" />
							<span class="positive"></span>
						</a>
					</div>
					<!-- Work Details -->
					<div class="work-bottom">
						<p class="work-name uppercase normal no-margin">Work image 9</p>
						<p class="work-category normal no-margin">Design</p>
						<a class="work-link-passive" ><span class="arrow"></span></a>
					</div>
				</div><!-- End Work Inner -->
			</div><!-- End Work -->

			<!-- Work -->
			<div class="work five photography design">
				<div class="work-inner">
					<!-- Image -->
					<div class="work-image">
						<a href="projects/project-5.html" class="expander">
							<img src="images/portfolio/10.jpg" alt="" />
							<span class="positive"></span>
						</a>
					</div>
					<!-- Work Details -->
					<div class="work-bottom">
						<p class="work-name uppercase normal no-margin">Work image 10</p>
						<p class="work-category normal no-margin">Design</p>
						<a class="work-link-passive" ><span class="arrow"></span></a>
					</div>
				</div><!-- End Work Inner -->
			</div><!-- End Work -->

			<!-- Clear -->
			<div class="clear"></div>
		</div><!-- End Works -->

</section><!-- End Porfolio Section -->

app/views/home/_projects.html.erb
<!-- Team -->
<section id="projects" class="container">
	
	<div class="inner">
		
		<h1 class="header bold dark">Our Projects</h1><br/><br/>
	
		<% @projects.each do |p| %>
			<div class="item">
				<h2 class="dark"><%= p.client %> |  <%= p.title %>
				<!--<input type="hidden" value=<%#= p.id %> class="modal-object-id">
				<a class="service-icon infome showButton" href="#projectShow">
					<i class="fa fa-info-circle"></i>
				</a>-->
				</h2>
				<div class="fitvids">
					<iframe src="//player.vimeo.com/video/<%= p.url %>?title=0&amp;byline=0&amp;portrait=0" width="500" height="282" 
					frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
				</div>
			</div><!-- //work1 -->
		<% end %>
		
		<%= render :partial => "modal" %>
	
	</div>
</section><!-- End Team Section -->

app/views/services/edit.html.erb
<%= render 'form' %>

app/views/services/new.html.erb
<%= render 'form' %>